// <auto-generated />
using System;
using BookBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookBackend.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookBackend.Modelos.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BookBackend.Modelos.Carnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("BookBackend.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BookBackend.Modelos.CondicionEjemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CondicionEjemplares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Bueno"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Regular"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.DetallePrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EjemplarId")
                        .HasColumnType("integer");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("DetallePrestamos");
                });

            modelBuilder.Entity("BookBackend.Modelos.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EjemplarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Ejemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("CondicionEjemplarId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoEjemplarId")
                        .HasColumnType("integer");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<string>("UbicacionEstante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("CondicionEjemplarId");

                    b.HasIndex("EstadoEjemplarId");

                    b.HasIndex("LibroId");

                    b.ToTable("Ejemplares");
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoEjemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoEjemplares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Prestado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Dañado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Perdido"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Vendido"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoPrestamos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Devuelto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Vencido"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoReservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cumplida"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadoVentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Completada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionRegistrada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EjemplarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspeccionadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoInspeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("InspeccionadoPorUsuarioId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("TipoInspeccionId");

                    b.ToTable("Inspecciones");
                });

            modelBuilder.Entity("BookBackend.Modelos.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioPublicacion")
                        .HasColumnType("integer");

                    b.Property<string>("Editorial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("BookBackend.Modelos.LibroAutor", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.HasKey("LibroId", "AutorId");

                    b.HasIndex("AutorId");

                    b.ToTable("LibroAutores");
                });

            modelBuilder.Entity("BookBackend.Modelos.LibroCategoria", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.HasKey("LibroId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("LibroCategorias");
                });

            modelBuilder.Entity("BookBackend.Modelos.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MetodoPagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tarjeta"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Transferencia"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("boolean");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoPrestamoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaDevolucionEsperada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDevolucionReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPrestamoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("BookBackend.Modelos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoReservaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoReservaId");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BookBackend.Modelos.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Revocada")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("BookBackend.Modelos.TipoInspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoInspecciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Salida"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Entrada"
                        });
                });

            modelBuilder.Entity("BookBackend.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BookBackend.Modelos.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("BookBackend.Modelos.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EstadoVentaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVentaId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Carnet", b =>
                {
                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithOne("Carnet")
                        .HasForeignKey("BookBackend.Modelos.Carnet", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.DetallePrestamo", b =>
                {
                    b.HasOne("BookBackend.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("DetallePrestamos")
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Prestamo", "Prestamo")
                        .WithMany("DetallePrestamos")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("BookBackend.Modelos.DetalleVenta", b =>
                {
                    b.HasOne("BookBackend.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BookBackend.Modelos.Ejemplar", b =>
                {
                    b.HasOne("BookBackend.Modelos.CondicionEjemplar", "CondicionEjemplar")
                        .WithMany("Ejemplares")
                        .HasForeignKey("CondicionEjemplarId");

                    b.HasOne("BookBackend.Modelos.EstadoEjemplar", "EstadoEjemplar")
                        .WithMany("Ejemplares")
                        .HasForeignKey("EstadoEjemplarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Libro", "Libro")
                        .WithMany("Ejemplares")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicionEjemplar");

                    b.Navigation("EstadoEjemplar");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BookBackend.Modelos.Inspeccion", b =>
                {
                    b.HasOne("BookBackend.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("Inspecciones")
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Usuario", "InspeccionadoPor")
                        .WithMany()
                        .HasForeignKey("InspeccionadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookBackend.Modelos.Prestamo", "Prestamo")
                        .WithMany("Inspecciones")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.TipoInspeccion", "TipoInspeccion")
                        .WithMany("Inspecciones")
                        .HasForeignKey("TipoInspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("InspeccionadoPor");

                    b.Navigation("Prestamo");

                    b.Navigation("TipoInspeccion");
                });

            modelBuilder.Entity("BookBackend.Modelos.LibroAutor", b =>
                {
                    b.HasOne("BookBackend.Modelos.Autor", "Autor")
                        .WithMany("LibroAutores")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Libro", "Libro")
                        .WithMany("LibroAutores")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BookBackend.Modelos.LibroCategoria", b =>
                {
                    b.HasOne("BookBackend.Modelos.Categoria", "Categoria")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Libro", "Libro")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BookBackend.Modelos.Multa", b =>
                {
                    b.HasOne("BookBackend.Modelos.Prestamo", "Prestamo")
                        .WithMany("Multas")
                        .HasForeignKey("PrestamoId");

                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany("Multas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.Prestamo", b =>
                {
                    b.HasOne("BookBackend.Modelos.EstadoPrestamo", "EstadoPrestamo")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstadoPrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoPrestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.Reserva", b =>
                {
                    b.HasOne("BookBackend.Modelos.EstadoReserva", "EstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Libro", "Libro")
                        .WithMany("Reservas")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoReserva");

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.Sesion", b =>
                {
                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.UsuarioRol", b =>
                {
                    b.HasOne("BookBackend.Modelos.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.Venta", b =>
                {
                    b.HasOne("BookBackend.Modelos.EstadoVenta", "EstadoVenta")
                        .WithMany("Ventas")
                        .HasForeignKey("EstadoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.MetodoPago", "MetodoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBackend.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("EstadoVenta");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BookBackend.Modelos.Autor", b =>
                {
                    b.Navigation("LibroAutores");
                });

            modelBuilder.Entity("BookBackend.Modelos.Categoria", b =>
                {
                    b.Navigation("LibroCategorias");
                });

            modelBuilder.Entity("BookBackend.Modelos.CondicionEjemplar", b =>
                {
                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("BookBackend.Modelos.Ejemplar", b =>
                {
                    b.Navigation("DetallePrestamos");

                    b.Navigation("DetalleVentas");

                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoEjemplar", b =>
                {
                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoPrestamo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BookBackend.Modelos.EstadoVenta", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Libro", b =>
                {
                    b.Navigation("Ejemplares");

                    b.Navigation("LibroAutores");

                    b.Navigation("LibroCategorias");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BookBackend.Modelos.MetodoPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Prestamo", b =>
                {
                    b.Navigation("DetallePrestamos");

                    b.Navigation("Inspecciones");

                    b.Navigation("Multas");
                });

            modelBuilder.Entity("BookBackend.Modelos.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("BookBackend.Modelos.TipoInspeccion", b =>
                {
                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("BookBackend.Modelos.Usuario", b =>
                {
                    b.Navigation("Carnet");

                    b.Navigation("Multas");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");

                    b.Navigation("Sesiones");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("BookBackend.Modelos.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
